name: Web Frontend

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1.1.0
    - name: Install
      run: npm --prefix web install
    - name: Build
      run: npm --prefix web run build
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v0.1.0
      env:
        GITHUB_PAT: ${{ secrets.GH_PAT }}
      with:
        target_branch: gh-pages
        build_dir: web/dist
